### ISSUE TITLE
Flowview errors cause it to become automatically disabled

### ISSUE THREAD

**Issue by fgont** [Cacti/plugin_flowview#50]
Folks,

I've just tried Cacti with the Flowview plugin, installing both of them from their respective github repos. I think I got everything up and running, with flow-capture feeding flow information into the plugin_flowview_raw_2020xxx table. However, before I was able to visualize any data/graphics, I realized that the "Flows" tab disappeared, and then found that the log was full of errors. Many/most of them were *tons* of these:

2020-06-22 15:01:37 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/flowview/flow_collector.php[341]:process_fv10(), /plugins/flowview/flow_collector.php[871]:CactiErrorHandler())
2020-06-22 15:01:37 - ERROR PHP NOTICE in Plugin 'flowview': Undefined offset: 1 in file: /usr/share/cacti-devel/plugins/flowview/flow_collector.php on line: 871
2020-06-22 15:01:37 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/flowview/flow_collector.php[341]:process_fv10(), /plugins/flowview/flow_collector.php[871]:CactiErrorHandler())
2020-06-22 15:01:37 - ERROR PHP NOTICE in Plugin 'flowview': Undefined offset: 1 in file: /usr/share/cacti-devel/plugins/flowview/flow_collector.php on line: 871
2020-06-22 15:01:37 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/flowview/flow_collector.php[341]:process_fv10(), /plugins/flowview/flow_collector.php[871]:CactiErrorHandler())

with one of the first ones being:

2020-06-22 11:51:07 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'flowview'
2020-06-22 11:51:07 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2020-06-22 11:51:07 - ERROR PHP ERROR in Plugin 'flowview': Uncaught Error: Call to undefined function curl_init() in /usr/share/cacti-devel/plugins/flowview/functions.php:3274 Stack trace: #0 /usr/share/cacti-devel/plugins/flowview/functions.php(3024): flowview_get_owner_from_arin('151.139.128.11') #1 /usr/share/cacti-devel/plugins/flowview/flow_collector.php(1012): flowview_get_dns_from_ip('151.139.128.11', 100) #2 /usr/share/cacti-devel/plugins/flowview/flow_collector.php(878): process_v9_v10(Array, '192.168.4.1:500...', 1592837472) #3 /usr/share/cacti-devel/plugins/flowview/flow_collector.php(341): process_fv10('\x00\n\x04L^\xF0\xC5`\x00\x00^.\x00\x00\x00...', '192.168.4.1:500...') #4 {main} thrown in file: /usr/share/cacti-devel/plugins/flowview/functions.php on line: 3274

The last error (first, cronologically speaking) seems to be the result of php-curl missing, which I dind't know was required, but I subsequently installed when I found out about the error message. I tried to re-enable Flowview from the Console -> Configuration/Settings -> Plugins, but it didn't work out.

Any clues about what might be going on?

Thanks!

Cheers,
Fernando

**Comment by TheWitness** [comment]
You need to install php-curl.

**Comment by TheWitness** [comment]
I've fixed the 871 bug today.  Please update.  Don't forget to install php-curl.
