### ISSUE TITLE
Flowview cannot enable in Cacti

### ISSUE THREAD

**Issue by apri1004** [Cacti/plugin_flowview#58]
Hi,

I'm new to Cacti and Flowview.
When I tried to enable flowview plugins, I get this error in log and somewhat the plugins is not enable.

"

2020-11-16 17:28:09 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'flowview'
--
2020-11-16 17:28:09 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2020-11-16 17:28:09 - ERROR PHP ERROR in Plugin 'flowview': Uncaught Error: Call to undefined function reports_get_format_files() in /var/www/html/cacti/plugins/flowview/setup.php:312 Stack trace: #0 /var/www/html/cacti/lib/plugins.php(177): flowview_config_settings() #1 /var/www/html/cacti/lib/plugins.php(74): api_plugin_run_plugin_hook() #2 /var/www/html/cacti/include/global_settings.php(2494): api_plugin_hook() #3 /var/www/html/cacti/include/global.php(505): include_once('/var/www/html/c...') #4 /var/www/html/cacti/include/auth.php(28): require_once('/var/www/html/c...') #5 /var/www/html/cacti/plugins.php(25): include('/var/www/html/c...') #6 {main} thrown in file: /var/www/html/cacti/plugins/flowview/setup.php on line: 312

"

Please help.

Thanks.
apri

**Comment by apri1004** [comment]
I make it work by modify setup.php in this plugins:

Original script:
------------------------------
function flowview_config_settings() {
        global $settings, $tabs;
        $formats = reports_get_format_files();
-------------------------------
Modified script:
-------------------------------
function flowview_config_settings() {
        global $config, $settings, $tabs;

        include_once($config['base_path'] . '/lib/reports.php');
        $formats = reports_get_format_files();
-------------------------------
After that no more error when enabling the plugins.

Thank you.

**Comment by TheWitness** [comment]
Good job.  Thanks.

**Comment by TheWitness** [comment]
Okay, fixed upstream.
